services:
  dashboard:
    build: .
    environment:
      VOIPMS_USER: ${VOIPMS_USER}
      VOIPMS_PASS: ${VOIPMS_PASS}
      DASHBOARD_AUTH: ${DASHBOARD_AUTH}
    labels:
      - traefik.http.services.voipms.loadbalancer.server.port=8000